services:
  app-db:
    image: postgres:16.2
    environment:
      POSTGRES_DB: innocode
      POSTGRES_USER: innocode
      POSTGRES_PASSWORD: innocode
    ports:
      - "5433:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  piston:
    image: ghcr.io/engineer-man/piston
    ports:
      - "2000:2000"
    volumes:
      - piston-packages:/piston/packages
    tmpfs:
      - /piston/jobs:exec
    privileged: true
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      DATABASE_URL: "postgresql://innocode:innocode@app-db:5432/innocode?schema=public"
      PISTON_URL: "http://piston:2000"
    volumes:
      - .:/app
      - web-node-modules:/app/node_modules
      - web-next-cache:/app/.next
    depends_on:
      - app-db
      - piston
    restart: unless-stopped

volumes:
  app-db-data:
  piston-packages:
  web-node-modules:
  web-next-cache:
