# Judge0 internal Postgres
POSTGRES_HOST=judge0-db
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0secret

# Judge0 internal Redis
REDIS_HOST=judge0-redis
REDIS_PASSWORD=judge0redis

# Judge0 runtime limits (MVP-safe)
MAX_QUEUE_SIZE=100
ENABLE_WAIT_RESULT=true
ALLOW_ENV_VARIABLES=false
